import { Technology } from '@/types/technology'

export const technologies: Array<Technology> = [
  // Basics
  { title: 'HTML',logo: 'devicon:html5' },
  { title: 'CSS', logo: 'devicon:css3' },
  { title: 'SCSS', logo: 'devicon:sass' },
  { title: 'JavaScript', logo: 'devicon:javascript' },
  { title: 'TypeScript', logo: 'devicon:typescript' },
  // React Stuff
  { title: 'React', logo: 'devicon:react' },
  { title: 'Next.js', logo: 'devicon:nextjs' },
  { title: 'Redux Toolkit', logo: 'skill-icons:redux' },
  { title: 'Zustand', logo: 'devicon:zustand' },
  { title: 'React Query', logo: 'logos:react-query-icon' },
  { title: 'React Router', logo: 'devicon:reactrouter' },
  { title: 'React Hook Form' },
  // { title: 'React Spring' },
  { title: 'SWR', logo:'simple-icons:swr' },
  { title: 'Formik',logo:'simple-icons:formik' },
  { title: 'NextAuth.js', logo:'simple-icons:auth0' },
  // UI Libraries
  { title: 'Tailwind CSS', logo: 'devicon:tailwindcss' },
  { title: 'Shadcn UI', logo: 'vscode-icons:file-type-shadcn' },
  { title: 'Radix UI',logo:'simple-icons:radixui' },
  { title: 'Chakra UI', logo:'devicon:chakraui' },
  { title: 'Mantine UI', logo:'logos:mantine-icon' },
  { title: 'Material UI',logo:'logos:material-ui' },
  { title: 'Styled-Components', logo:'devicon:styledcomponents' },
  // { title: 'React Aria' },
  { title: 'Framer Motion', logo: 'tabler:brand-framer-motion' },
  // Utilities
  { title: 'NPM', logo: 'devicon:npm' },
  { title: 'Git', logo: 'devicon:git' },
  { title: 'GitHub', logo: 'simple-icons:github' },
  { title: 'Vercel',logo:'skill-icons:vercel-dark' },
  { title: 'Webpack', logo: 'devicon:webpack' },
  { title: 'Babel', logo: 'material-icon-theme:babel' },
  { title: 'Vite',logo:'skill-icons:vite-dark' },
  { title: 'ESLint',logo:'devicon:eslint' },
  { title: 'Prettier', logo: 'material-icon-theme:prettier' },
  { title: 'Jest', logo: 'skill-icons:jest' },
  { title: 'React Testing Library' },
  { title: 'Playwright',logo:'devicon:playwright' },
  { title: 'Cypress', logo: 'skill-icons:cypress-light' },
  { title: 'Vitest', logo: 'devicon:vitest' },
  // { title: 'Storybook' },
  // { title: 'GraphQL' },
  { title: 'Axios', logo: 'simple-icons:axios' },
  { title: 'Websocket', logo: 'simple-icons:socketdotio' },
  // { title: 'Apollo Client' },
  // { title: 'Firebase' },
  { title: 'Supabase',logo:'devicon:supabase' },
  // { title: 'Prisma' },
  { title: 'Zod', logo: 'logos:zod' },
  { title: 'Lodash',logo:'devicon:lodash' },
]
