import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'
import Navbar from '@/app/_components/Navbar'
import Link from 'next/link'
import { Icon } from '@iconify/react'

const outfit = Outfit({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Ali Kouhfar - Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: <{
  children: ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${outfit.className} bg-[#0a0a0a] antialiased`}>
        <main className="relative mx-auto mt-32 flex w-full max-w-7xl flex-col items-center justify-center px-8 md:mt-36">
          <div className="pointer-events-none fixed top-0 left-1/2 z-40 h-24 w-full -translate-x-1/2">
            <div className="absolute inset-0 overflow-hidden">
              <div
                className="pointer-events-none absolute inset-0 z-10 opacity-100"
                style={{
                  backdropFilter: 'blur(3px)',
                  maskImage:
                    'linear-gradient(to top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 1) 40%, rgba(0, 0, 0, 1) 70%, rgba(0, 0, 0, 0) 100%);-webkit-mask-image:linear-gradient(to top, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 1) 40%, rgba(0, 0, 0, 1) 70%, rgba(0, 0, 0, 0) 100%)',
                }}
              />
              <div
                className="pointer-events-none absolute inset-0 z-20 opacity-100"
                style={{
                  backdropFilter: 'blur(5px)',
                  maskImage:
                    'linear-gradient(to top, rgba(0, 0, 0, 0) 60%, rgba(0, 0, 0, 1) 85%, rgba(0, 0, 0, 1) 100%);-webkit-mask-image:linear-gradient(to top, rgba(0, 0, 0, 0) 60%, rgba(0, 0, 0, 1) 85%, rgba(0, 0, 0, 1) 100%)',
                }}
              />
            </div>
          </div>
          <Navbar />
          {children}
          <section id="contact" className="relative my-20 flex w-full justify-center">
            <div className="relative z-10 mx-auto flex w-full max-w-6xl flex-col items-center justify-center gap-y-2 py-10 text-center lg:mx-0">
              <div className="group" style={{ transform: 'none' }}>
                <button className="group relative my-10 inline-flex cursor-pointer items-center justify-between overflow-hidden rounded-full border border-black/30 bg-black/20 py-[3px] pr-[3px] pl-2 text-base font-medium opacity-85 backdrop-blur-xs transition-all group-hover:scale-125 hover:bg-transparent md:py-1 md:pr-1 md:pl-3 dark:border-white/10 dark:bg-white/10">
                  <span className="z-10 px-3 text-black transition-colors duration-300 group-hover:text-white dark:text-white dark:group-hover:text-black">
                    Get In Touch
                  </span>
                  <span className="absolute inset-0 translate-x-[45%] scale-0 rounded-full bg-black opacity-0 transition-all duration-300 ease-in-out group-hover:translate-x-0 group-hover:scale-100 group-hover:opacity-100 dark:bg-white"></span>
                  <span className="z-10 flex items-center justify-center overflow-hidden rounded-full bg-black p-2 transition-colors duration-300 group-hover:bg-transparent md:p-2.5 dark:bg-white">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="18"
                      height="18"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="lucide lucide-arrow-right text-white transition-all duration-300 group-hover:translate-x-5 group-hover:opacity-0 dark:text-black"
                      aria-hidden="true"
                    >
                      <path d="M5 12h14"></path>
                      <path d="m12 5 7 7-7 7"></path>
                    </svg>
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      width="18"
                      height="18"
                      viewBox="0 0 24 24"
                      fill="none"
                      stroke="currentColor"
                      strokeWidth="2"
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      className="lucide lucide-arrow-right absolute -translate-x-5 text-white opacity-0 transition-all duration-300 group-hover:translate-x-0 group-hover:opacity-100 dark:text-black"
                      aria-hidden="true"
                    >
                      <path d="M5 12h14"></path>
                      <path d="m12 5 7 7-7 7"></path>
                    </svg>
                  </span>
                </button>
              </div>
              <p className="tracking-wid text-base font-semibold lg:text-2xl">
                Available for full-time or contract opportunities.
              </p>
              <p className="my-2 text-sm font-extralight tracking-wide text-balance opacity-75 lg:text-xl">
                I build fast, responsive web apps that users
                <br />
                love—melding functionality with flawless UI.
              </p>
            </div>
          </section>
          <footer className="mx-auto my-6 w-full max-w-6xl max-lg:px-4">
            <div className="bg-white-2 relative mx-auto flex flex-col items-center gap-6 rounded-3xl px-4 py-10 shadow-sm backdrop-blur-lg md:flex-row dark:bg-white/[0.02]">
              <div className="flex flex-1 flex-col items-start gap-4 md:flex-row md:gap-10 md:px-8">
                <div className="hidden flex-col gap-y-6 md:flex md:w-1/2">
                  <Link className="inline-block" href="/">
                    LOGO
                  </Link>
                  <p className="w-60 text-sm leading-5 dark:text-gray-300">
                    I'm Ali - a frontend developer, UI craftsman &amp; creative problem solver. Thanks for
                    stopping by!
                  </p>
                </div>
                <div className="flex flex-col items-start justify-between gap-6 md:mx-4 md:w-1/2 md:flex-row md:gap-16">
                  <div className="flex flex-col gap-2 md:gap-4">
                    <h4 className="text-base text-neutral-700 dark:text-white">General</h4>
                    <ul className="flex flex-wrap items-start gap-x-4 gap-y-2 text-sm md:flex-col md:gap-y-3 dark:text-neutral-300">
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/"
                        >
                          Home
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/about"
                        >
                          About
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/projects"
                        >
                          Projects
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/blog"
                        >
                          Blog
                        </a>
                      </li>
                    </ul>
                  </div>
                  <div className="flex flex-col gap-2 md:gap-4">
                    <h4 className="text-base text-neutral-700 dark:text-white">Specifics</h4>
                    <ul className="flex flex-wrap items-start gap-x-4 gap-y-2 text-sm md:flex-col md:gap-y-3 dark:text-neutral-300">
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/guestbook"
                        >
                          Guest Book
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/bucket-list"
                        >
                          Bucket List
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/uses"
                        >
                          Uses
                        </a>
                      </li>
                      <li className="pointer-events-none opacity-50">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/attribution"
                        >
                          Attribution
                        </a>
                      </li>
                    </ul>
                  </div>
                  <div className="flex flex-col gap-2 md:gap-4">
                    <h4 className="text-base text-neutral-700 dark:text-white">More</h4>
                    <ul className="flex flex-wrap items-start gap-x-4 gap-y-2 text-sm md:flex-col md:gap-y-3 dark:text-neutral-300">
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/contact"
                        >
                          Book a call
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/links"
                        >
                          Links
                        </a>
                      </li>
                      <li className="">
                        <a
                          className="after:bg-primary relative after:absolute after:bottom-0 after:left-0 after:h-px after:w-full after:origin-bottom-right after:scale-x-0 after:transition-transform after:duration-300 after:ease-in-out hover:after:origin-bottom-left hover:after:scale-x-100"
                          href="/rss"
                        >
                          RSS
                        </a>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="mt-4 flex flex-col items-center justify-between gap-4 text-sm text-neutral-600 md:flex-row md:px-8 dark:text-neutral-400">
              <div className="flex flex-col items-center gap-3 sm:flex-row sm:gap-6">
                <p className="whitespace-nowrap">
                  &copy; 2025
                  <Link
                    className="ml-1 whitespace-nowrap transition-colors hover:text-black dark:hover:text-white"
                    href="/"
                  >
                    Ali Kouhfar
                  </Link>
                  . All rights reserved
                </p>
                <div className="flex items-center justify-center gap-4 sm:gap-6">
                  <a
                    className="whitespace-nowrap transition-colors hover:text-black dark:hover:text-white"
                    href="/legal/privacy"
                  >
                    Privacy Policy
                  </a>
                  <a
                    className="whitespace-nowrap transition-colors hover:text-black dark:hover:text-white"
                    href="/legal/terms"
                  >
                    Terms &amp; Conditions
                  </a>
                </div>
              </div>
              <div className="flex flex-col items-center gap-4 md:flex-row md:justify-end">
                <div className="flex gap-3">
                  <Link
                    target="_blank"
                    href="https://instagram.com/ali.kouhfar"
                    className="transition-all duration-300 hover:scale-105 hover:text-indigo-500"
                  >
                    <Icon icon="simple-icons:instagram" width="18" />
                  </Link>
                  <Link
                    target="_blank"
                    href="https://github.com/alikouhfar"
                    className="transition-all duration-300 hover:scale-105 hover:text-indigo-500"
                  >
                    <Icon icon="simple-icons:github" width="18" />
                  </Link>
                  <Link
                    target="_blank"
                    href="https://linkedin.com/in/alikouhfar"
                    className="transition-all duration-300 hover:scale-105 hover:text-indigo-500"
                  >
                    <Icon icon="simple-icons:linkedin" width="18" />
                  </Link>
                </div>
              </div>
            </div>
          </footer>
        </main>
      </body>
    </html>
  )
}
