import { Locale } from '@/app/[lang]/dictionaries'
import { Skill } from '@/types/skill'
import {
  IconAccessible,
  IconApi,
  IconBolt,
  IconBrandGithub,
  IconCode,
  IconCpu,
  IconDeviceMobile,
  IconForms,
  IconLayersIntersect,
  IconLayout,
  IconPalette,
  IconStack,
  IconTestPipe,
} from '@tabler/icons-react'

export const SKILLS: Record<Locale, Skill[]> = {
  en: [
    {
      id: 'a3f1c8d2-7b44-4e9a-9c11-6f2d8b7e1a11',
      name: 'React / Next.js',
      icon: <IconCode className="h-6 w-6" />,
      desc: 'Building scalable, SSR/CSR hybrid applications with modern React architecture.',
      size: 'large',
    },
    {
      id: 'c7d2f1a8-3e55-4b9c-8f11-2d7a6c1b9e22',
      name: 'TypeScript',
      icon: <IconCpu className="h-6 w-6" />,
      desc: 'Designing robust, type-safe and maintainable frontend systems.',
      size: 'medium',
    },
    {
      id: 'f2b7c1d9-6a33-4e8c-9a11-7d2b5c8e1f33',
      name: 'State Management',
      icon: <IconStack className="h-6 w-6" />,
      desc: 'Managing server and client state using React Query, Zustand, and context patterns.',
      size: 'medium',
    },
    {
      id: 'e1c9a7f2-5b44-4d8c-9f11-3a7d2c8b6e44',
      name: 'Data Fetching & Caching',
      icon: <IconApi className="h-6 w-6" />,
      desc: 'Handling asynchronous data, caching, and synchronization strategies.',
      size: 'small',
    },
    {
      id: 'b8f1c7a2-6d33-4e9b-8c11-7f2d9a5c1e55',
      name: 'Forms & Validation',
      icon: <IconForms className="h-6 w-6" />,
      desc: 'Building complex, dynamic forms with validation (React Hook Form, Zod).',
      size: 'small',
    },
    {
      id: 'd2a7c1f8-5e44-4b9c-9a11-6f2d8c7b1e66',
      name: 'Performance Optimization',
      icon: <IconBolt className="h-6 w-6" />,
      desc: 'Code splitting, memoization, lazy loading, and rendering optimization.',
      size: 'small',
    },
    {
      id: 'a9c1f7d2-3b44-4e8c-9f11-7d2b6c8e5a77',
      name: 'Component Architecture',
      icon: <IconLayout className="h-6 w-6" />,
      desc: 'Designing reusable, scalable, and maintainable component systems.',
      size: 'small',
    },
    {
      id: 'f3b7c2a1-6e33-4d9c-8f11-2d7a5c8b1e88',
      name: 'Tailwind CSS',
      icon: <IconPalette className="h-6 w-6" />,
      desc: 'Crafting responsive, utility-first UI with consistent design systems.',
      size: 'medium',
    },
    {
      id: 'c1d8a7f2-5b44-4e9c-9a11-6f2d7b8c1e99',
      name: 'Responsive Design',
      icon: <IconDeviceMobile className="h-6 w-6" />,
      desc: 'Building adaptive layouts for all screen sizes and devices.',
      size: 'medium',
    },
    {
      id: 'e9a1c7f2-6b33-4d8c-8f11-3a7d2c8b5e00',
      name: 'Animations',
      icon: <IconLayersIntersect className="h-6 w-6" />,
      desc: 'Creating smooth UI interactions and transitions with modern animation libraries.',
      size: 'small',
    },
    {
      id: 'b2f7c1d9-5e44-4a8c-9f11-7d2b6c8e1a11',
      name: 'Accessibility (a11y)',
      icon: <IconAccessible className="h-6 w-6" />,
      desc: 'Ensuring inclusive interfaces following accessibility standards.',
      size: 'small',
    },
    {
      id: 'd7c1a8f2-6b33-4e9c-8f11-2d7a5c8b1e22',
      name: 'Git & Collaboration',
      icon: <IconBrandGithub className="h-6 w-6" />,
      desc: 'Version control, code reviews, and collaborative workflows.',
      size: 'large',
    },
    {
      id: 'a1f7c2d9-5b44-4e8c-9f11-6d2b8c7e3a33',
      name: 'Testing',
      icon: <IconTestPipe className="h-6 w-6" />,
      desc: 'Writing unit and integration tests for reliable UI behavior.',
      size: 'medium',
    },
  ],

  de: [
    {
      id: 'c8f1a7d2-3b44-4e9c-9a11-7d2b6c8e5a44',
      name: 'React / Next.js',
      icon: <IconCode className="h-6 w-6" />,
      desc: 'Entwicklung skalierbarer Anwendungen mit moderner React-Architektur (SSR/CSR).',
      size: 'large',
    },
    {
      id: 'e1b7c2f9-6d33-4a8c-9f11-3a7d8c2b5e55',
      name: 'TypeScript',
      icon: <IconCpu className="h-6 w-6" />,
      desc: 'Erstellung robuster und typsicherer Frontend-Systeme.',
      size: 'medium',
    },
    {
      id: 'f2c1a7d9-5b44-4e9c-8f11-7d2b6c8e1a66',
      name: 'State Management',
      icon: <IconStack className="h-6 w-6" />,
      desc: 'Verwaltung von Server- und Client-Zustand mit React Query, Zustand und Context.',
      size: 'medium',
    },
    {
      id: 'a9c7f1d2-6b33-4e8c-9f11-2d7b5c8e1a77',
      name: 'Data Fetching & Caching',
      icon: <IconApi className="h-6 w-6" />,
      desc: 'Asynchrone Datenverarbeitung, Caching und Synchronisation.',
      size: 'small',
    },
    {
      id: 'd2f7c1a8-5e44-4b9c-9f11-6d2b8c7e1a88',
      name: 'Forms & Validierung',
      icon: <IconForms className="h-6 w-6" />,
      desc: 'Erstellung komplexer Formulare mit Validierung (React Hook Form, Zod).',
      size: 'small',
    },
    {
      id: 'b8c1f7d2-6e33-4a9c-8f11-7d2b5c8e1a99',
      name: 'Performance Optimierung',
      icon: <IconBolt className="h-6 w-6" />,
      desc: 'Code-Splitting, Memoisierung und Rendering-Optimierung.',
      size: 'small',
    },
    {
      id: 'e9c1a7f2-5b44-4d8c-9f11-6d2b8c7e1b00',
      name: 'Komponentenarchitektur',
      icon: <IconLayout className="h-6 w-6" />,
      desc: 'Entwurf wiederverwendbarer und skalierbarer Komponenten.',
      size: 'small',
    },
    {
      id: 'c1f7a8d2-6b33-4e9c-8f11-2d7b5c8e1b11',
      name: 'Tailwind CSS',
      icon: <IconPalette className="h-6 w-6" />,
      desc: 'Gestaltung responsiver UI mit Utility-First-Ansatz.',
      size: 'medium',
    },
    {
      id: 'a7d1c2f8-5b44-4e8c-9f11-6d2b8c7e1b22',
      name: 'Responsive Design',
      icon: <IconDeviceMobile className="h-6 w-6" />,
      desc: 'Anpassung an verschiedene Bildschirmgrößen.',
      size: 'medium',
    },
    {
      id: 'f3c1a7d2-6b33-4e9c-8f11-7d2b5c8e1b33',
      name: 'Animationen',
      icon: <IconLayersIntersect className="h-6 w-6" />,
      desc: 'Erstellung flüssiger UI-Animationen.',
      size: 'small',
    },
    {
      id: 'b2c7f1a8-5e44-4d9c-9f11-6d2b8c7e1b44',
      name: 'Accessibility (a11y)',
      icon: <IconAccessible className="h-6 w-6" />,
      desc: 'Barrierefreie Benutzeroberflächen nach Standards.',
      size: 'small',
    },
    {
      id: 'd7a1c2f8-6b33-4e9c-8f11-2d7b5c8e1b55',
      name: 'Git & Zusammenarbeit',
      icon: <IconBrandGithub className="h-6 w-6" />,
      desc: 'Versionskontrolle und Teamarbeit.',
      size: 'medium',
    },
    {
      id: 'a1c7f2d8-5b44-4e8c-9f11-6d2b8c7e1b66',
      name: 'Testing',
      icon: <IconTestPipe className="h-6 w-6" />,
      desc: 'Unit- und Integrationstests für stabile Anwendungen.',
      size: 'large',
    },
  ],

  fa: [
    {
      id: 'c8a1f7d2-6b33-4e9c-8f11-7d2b5c8e1c11',
      name: 'React / Next.js',
      icon: <IconCode className="h-6 w-6" />,
      desc: 'توسعه اپلیکیشن‌های مقیاس‌پذیر با معماری مدرن React (SSR/CSR).',
      size: 'large',
    },
    {
      id: 'e1c7f2a8-5b44-4e9c-9f11-6d2b8c7e1c22',
      name: 'TypeScript',
      icon: <IconCpu className="h-6 w-6" />,
      desc: 'ایجاد سیستم‌های فرانت‌اند تایپ‌سیف و قابل نگهداری.',
      size: 'medium',
    },
    {
      id: 'd2a7c1f8-6b33-4e8c-9f11-7d2b5c8e1c33',
      name: 'مدیریت وضعیت',
      icon: <IconStack className="h-6 w-6" />,
      desc: 'مدیریت وضعیت کلاینت و سرور با React Query، Zustand و Context.',
      size: 'medium',
    },
    {
      id: 'b8c1f7a2-5e44-4d9c-8f11-6d2b8c7e1c44',
      name: 'دریافت و کش داده',
      icon: <IconApi className="h-6 w-6" />,
      desc: 'مدیریت داده‌های غیرهمزمان، کشینگ و همگام‌سازی.',
      size: 'small',
    },
    {
      id: 'f2c7a1d8-6b33-4e9c-8f11-7d2b5c8e1c55',
      name: 'فرم و اعتبارسنجی',
      icon: <IconForms className="h-6 w-6" />,
      desc: 'ساخت فرم‌های پیچیده با اعتبارسنجی (React Hook Form، Zod).',
      size: 'small',
    },
    {
      id: 'a9f1c7d2-5b44-4e8c-9f11-6d2b8c7e1c66',
      name: 'بهینه‌سازی عملکرد',
      icon: <IconBolt className="h-6 w-6" />,
      desc: 'بهینه‌سازی رندر، lazy loading و code splitting.',
      size: 'small',
    },
    {
      id: 'c1a7f2d8-6b33-4e9c-8f11-7d2b5c8e1c77',
      name: 'معماری کامپوننت',
      icon: <IconLayout className="h-6 w-6" />,
      desc: 'طراحی کامپوننت‌های قابل استفاده مجدد و مقیاس‌پذیر.',
      size: 'small',
    },
    {
      id: 'e9b7c1a2-5b44-4d8c-9f11-6d2b8c7e1c88',
      name: 'Tailwind CSS',
      icon: <IconPalette className="h-6 w-6" />,
      desc: 'طراحی رابط کاربری واکنش‌گرا با رویکرد utility-first.',
      size: 'medium',
    },
    {
      id: 'd7c1a2f8-6b33-4e9c-8f11-7d2b5c8e1c99',
      name: 'طراحی واکنش‌گرا',
      icon: <IconDeviceMobile className="h-6 w-6" />,
      desc: 'سازگاری با اندازه‌های مختلف صفحه.',
      size: 'medium',
    },
    {
      id: 'b2a7c1f8-5b44-4e8c-9f11-6d2b8c7e1d00',
      name: 'انیمیشن',
      icon: <IconLayersIntersect className="h-6 w-6" />,
      desc: 'ایجاد تعاملات و انیمیشن‌های روان.',
      size: 'small',
    },
    {
      id: 'f3c1a7d2-6b33-4e9c-8f11-7d2b5c8e1d11',
      name: 'دسترس‌پذیری (a11y)',
      icon: <IconAccessible className="h-6 w-6" />,
      desc: 'رعایت استانداردهای دسترس‌پذیری در رابط کاربری.',
      size: 'small',
    },
    {
      id: 'a1b7c2f8-5b44-4e8c-9f11-6d2b8c7e1d22',
      name: 'تست‌نویسی',
      icon: <IconTestPipe className="h-6 w-6" />,
      desc: 'نوشتن تست برای پایداری رفتار UI.',
      size: 'large',
    },
    {
      id: 'c8f1a7d2-6b33-4e9c-8f11-7d2b5c8e1d33',
      name: 'Git و همکاری تیمی',
      icon: <IconBrandGithub className="h-6 w-6" />,
      desc: 'کنترل نسخه و همکاری در تیم.',
      size: 'medium',
    },
  ],
}
