import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import './globals.css'
import { ReactNode } from 'react'

const outfit = Outfit({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Ali Kouhfar - Frontend Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${outfit.className} bg-[#0a0a0a] antialiased`}>{children}</body>
    </html>
  )
}
